.pragma library

// SomaFM categories - these should ONLY contain SomaFM stations
var somafmCategories = [
    {
        "name": "🌙 Ambient",
        "stations": [
            { "name": "Groove Salad", "host": "https://somafm.com", "path": "groovesalad", "description": "A nicely chilled plate of ambient/downtempo beats and grooves." },
            { "name": "Drone Zone", "host": "https://somafm.com", "path": "dronezone", "description": "Atmospheric textures with minimal beats." },
            { "name": "Deep Space One", "host": "https://somafm.com", "path": "deepspaceone", "description": "Deep ambient electronic and space music." },
            { "name": "Mission Control", "host": "https://somafm.com", "path": "missioncontrol", "description": "Celebrating NASA and Space Explorers everywhere." },
            { "name": "Fluid", "host": "https://somafm.com", "path": "fluid", "description": "Dj-mixed chillout, new age and ambient." },
            { "name": "Sf 10 - 33", "host": "https://somafm.com", "path": "sf1033", "description": "Ambient music mixed with the sounds of San Francisco public safety radio traffic." }
        ]
    },
    {
        "name": "⚡ Electro & Beats",
        "stations": [
            { "name": "Space Station Soma", "host": "https://somafm.com", "path": "spacestation", "description": "Tune in, turn on, space out." },
            { "name": "Beat Blender", "host": "https://somafm.com", "path": "beatblender", "description": "A late night blend of deep-house and downtempo chill." },
            { "name": "Poptron", "host": "https://somafm.com", "path": "poptron", "description": "Electropop and indie dance rock with sparkle and pop." },
            { "name": "The Trip", "host": "https://somafm.com", "path": "thetrip", "description": "Progressive house / trance. Tip top tunes." },
            { "name": "Underground 80s", "host": "https://somafm.com", "path": "u80s", "description": "Early 80s UK Synthpop and a bit of New Wave." },
            { "name": "Digitalis", "host": "https://somafm.com", "path": "digitalis", "description": "Digitally influenced electronic music." },
            { "name": "Cliqhop IDM", "host": "https://somafm.com", "path": "cliqhop", "description": "Blips'n'beats and other clicks and cuts." },
            { "name": "Earwaves", "host": "https://somafm.com", "path": "earwaves", "description": "Spanning the electronic spectrum." },
            { "name": "Dubstep Beyond", "host": "https://somafm.com", "path": "dubstep", "description": "Dubstep, future garage and the wobbles." },
            { "name": "Def Con Radio", "host": "https://somafm.com", "path": "defcon", "description": "Music for Hacking. The DEF CON Year-Round Channel." }
        ]
    },
    {
        "name": "🎸 Rock & Alternative",
        "stations": [
            { "name": "Indie Pop Rocks!", "host": "https://somafm.com", "path": "indiepop", "description": "New and classic favorite indie pop tracks." },
            { "name": "Left Coast 70s", "host": "https://somafm.com", "path": "leftcoast70s", "description": "New and classic west coast rock and folk." },
            { "name": "Metal Detector", "host": "https://somafm.com", "path": "metal", "description": "From the underground comes the loudest SomaFM channel." },
            { "name": "Bagel Radio", "host": "https://somafm.com", "path": "bagel", "description": "What alternative rock radio should sound like." }
        ]
    },
    {
        "name": "🍸 Lounge & Chill",
        "stations": [
            { "name": "Illinois Street Lounge", "host": "https://somafm.com", "path": "illstreet", "description": "Classic bachelor pad, playful exotica and vintage music." },
            { "name": "Secret Agent", "host": "https://somafm.com", "path": "secretagent", "description": "The soundtrack for your stylish, mysterious, dangerous life." },
            { "name": "Lush", "host": "https://somafm.com", "path": "lush", "description": "Sensuous and mellow female vocals, mostly with an electronic influence." },
            { "name": "Seven Inch Soul", "host": "https://somafm.com", "path": "7soul", "description": "Vintage soul tracks from the original 45 RPM vinyl." }
        ]
    },
    {
        "name": "🌍 Folk & World",
        "stations": [
            { "name": "Thistleradio", "host": "https://somafm.com", "path": "thistle", "description": "Exploring music from Celtic roots and branches." },
            { "name": "Folk Forward", "host": "https://somafm.com", "path": "folkfwd", "description": "Indie Folk, Alt-folk and the occasional folk classics." },
            { "name": "Suburbs of Goa", "host": "https://somafm.com", "path": "suburbsofgoa", "description": "Desi-influenced Asian world beats and beyond." },
            { "name": "Boot Liquor", "host": "https://somafm.com", "path": "bootliquor", "description": "Americana Roots music for Cowhands, Cowpokes and Cowtippers." }
        ]
    },
    {
        "name": "🎷 Jazz & Experimental",
        "stations": [
            { "name": "Sonic Universe", "host": "https://somafm.com", "path": "sonicuniverse", "description": "Transcending the world of jazz with eclectic, avant-garde takes on tradition." }
        ]
    },
    {
        "name": "🔥 Specials",
        "stations": [
            { "name": "Black Rock FM", "host": "https://somafm.com", "path": "brfm", "description": "From the Playa to the world, for the annual Burning Man festival." }
        ]
    }
]

// RadCap categories - these should ONLY contain RadCap stations
var radcapCategories = [
{
        "name": "Ethnic / Folk / Spiritual",
        "stations": [
            { "name": "Indian Classical / Folk / Ethnic", "host": "http://79.111.14.76", "path": "indianfolk" },
            { "name": "Russian Folk", "host": "http://79.111.14.76", "path": "folkrockru" },
            { "name": "Orthodox Spiritual Music", "host": "http://79.111.14.76", "path": "orthodox" },
            { "name": "Flamenco", "host": "http://79.111.14.76", "path": "flamenco" },
            { "name": "Tango", "host": "http://79.120.39.202", "path": "tango" },
            { "name": "Middle Eastern Music", "host": "http://79.111.119.111", "path": "middleeast" },
            { "name": "Celtic", "host": "http://79.120.12.130", "path": "celticrock" },
            { "name": "Native American", "host": "http://79.111.119.111", "path": "nativeamerican" },
            { "name": "Traditional Latin Music", "host": "http://79.120.39.202", "path": "salsa" },
            { "name": "Far Eastern Music", "host": "http://79.120.12.130", "path": "freestyle" },
            { "name": "Balkan Music", "host": "http://79.120.39.202", "path": "balkan" },
            { "name": "Jewish Music / Klezmer", "host": "http://79.120.39.202", "path": "klezmer" },
            { "name": "Laiko / Greek Music", "host": "http://79.111.119.111", "path": "laika" },
            { "name": "African Folk / Ethnic", "host": "http://79.120.39.202", "path": "africanfolk" },
            { "name": "Caucasian Music", "host": "http://213.141.131.10", "path": "caucasus" },
            { "name": "Americana", "host": "http://213.141.131.10", "path": "americana" },
            { "name": "Gospel / Spirituals Music", "host": "http://79.111.14.76", "path": "gospel" },
            { "name": "Music of Siberia / Mongolia", "host": "http://79.111.119.111", "path": "siberia" },
            { "name": "Indian Spiritual Music", "host": "http://79.111.14.76", "path": "orthodox" },
            { "name": "Medieval Folk", "host": "http://213.141.131.10", "path": "medievalfolk" },
            { "name": "European Folk", "host": "http://213.141.131.10", "path": "europeanfolk" },
            { "name": "Fado", "host": "http://213.141.131.10", "path": "fado" },
            { "name": "Slavonic Neofolk", "host": "http://213.141.131.10", "path": "slavonicneofolk" },
            { "name": "Oceania / Australia / ...", "host": "http://213.141.131.10", "path": "oceania" },
            { "name": "Andean / South American Music", "host": "http://213.141.131.10", "path": "andean" },
            { "name": "Zydeco / Cajun / Creole Music", "host": "http://213.141.131.10", "path": "zydeco" },
            { "name": "Afrobeat / Afrobeats", "host": "http://79.120.39.202", "path": "afrobeat" },
        ]
    },
    {
        "name": "Classical Music",
        "stations": [
            { "name": "Symphony", "host": "http://79.111.14.76", "path": "symphony" },
            { "name": "Classical Piano", "host": "http://79.120.39.202", "path": "classpiano" },
            { "name": "Symphonic Music", "host": "http://79.120.39.202", "path": "symphorock" },
            { "name": "Classical Choral / Vocal Music", "host": "http://79.120.39.202", "path": "chorus" },
            { "name": "Organ Music", "host": "http://79.120.77.11", "path": "organ" },
            { "name": "Classical Baroque", "host": "http://79.111.14.76", "path": "baroque" },
            { "name": "Opera", "host": "http://79.120.39.202", "path": "opera" },
            { "name": "Strings", "host": "http://79.120.39.202", "path": "strings" },
            { "name": "Contemporary Classical", "host": "http://79.111.119.111", "path": "contclass" },
            { "name": "Renaissance Music", "host": "http://213.141.131.10", "path": "renaissance" },
            { "name": "Medieval Music", "host": "http://213.141.131.10", "path": "medieval" },
            { "name": "Chamber Music", "host": "http://213.141.131.10", "path": "chamber" },
            { "name": "Clavecin / Cembalo / Harpsichord", "host": "http://213.141.131.10", "path": "clavecin" },
            { "name": "Cello / Violoncello", "host": "http://79.120.12.130", "path": "cello" },
            { "name": "Violin", "host": "http://213.141.131.10", "path": "violin" },
            { "name": "Clarinet / Bassoon / Oboe", "host": "http://213.141.131.10", "path": "clarinet" },
            { "name": "Classical Guitar", "host": "http://213.141.131.10", "path": "classguitar" },
            { "name": "Harp", "host": "http://213.141.131.10", "path": "harp" },
            { "name": "Christian Sacred Music", "host": "http://213.141.131.10", "path": "sacred" },
            { "name": "Impressionism", "host": "http://79.120.12.130", "path": "impressionism" },
            { "name": "Sonatas", "host": "http://213.141.131.10", "path": "sonata" },
            { "name": "Chants / Gregorian Chants", "host": "http://213.141.131.10", "path": "chants" },
            { "name": "Classical Avant - Garde", "host": "http://213.141.131.10", "path": "classavant" },
            { "name": "Minimalism / Postminimalism", "host": "http://213.141.131.10", "path": "minimalism" },
            { "name": "Lute / Archlute / Theorbo", "host": "http://79.120.12.130", "path": "lute" },
            { "name": "Cantatas", "host": "http://79.120.12.130", "path": "cantata" },
            { "name": "Oratorios", "host": "http://79.120.12.130", "path": "cantata" },
            { "name": "Classical Flute", "host": "http://79.111.14.76", "path": "fluteclass" },
        ]
    },
    {
        "name": "Blues / Funk / Soul / R & B",
        "stations": [
            { "name": "Acoustic Blues", "host": "http://79.111.14.76", "path": "acousticblues" },
            { "name": "Soul / Neo Soul", "host": "http://79.120.39.202", "path": "soul" },
            { "name": "Delta Blues", "host": "http://79.120.77.11", "path": "deltablues" },
            { "name": "Funk", "host": "http://79.111.119.111", "path": "funk" },
            { "name": "Harmonica Blues", "host": "http://79.120.39.202", "path": "harpblues" },
            { "name": "Country / Folk Blues", "host": "http://79.120.77.11", "path": "countryblues" },
            { "name": "Piano Blues / Boogie - Woogie", "host": "http://79.111.14.76", "path": "pianoblues" },
            { "name": "R'n'b", "host": "http://79.120.77.11", "path": "rnb" },
            { "name": "Chicago Blues", "host": "http://79.111.14.76", "path": "chicagoblues" },
            { "name": "Heavy / Hard Blues", "host": "http://79.120.77.11", "path": "heavyblues" },
            { "name": "Blues", "host": "http://79.120.77.11", "path": "blues" },
            { "name": "Electric / Modern Electric Blues", "host": "http://79.111.14.76", "path": "electricblues" },
            { "name": "Soul Blues", "host": "http://79.111.14.76", "path": "soulblues" },
            { "name": "Texas Blues", "host": "http://79.111.14.76", "path": "texasblues" },
            { "name": "Pop Soul", "host": "http://213.141.131.10", "path": "popsoul" },
            { "name": "Jump Blues", "host": "http://213.141.131.10", "path": "jumpblues" },
            { "name": "Louisiana / Swamp / New Orleans Blues", "host": "http://213.141.131.10", "path": "louisianablues" },
            { "name": "Slide Guitar", "host": "http://213.141.131.10", "path": "slideguitar" },
            { "name": "West Coast Blues", "host": "http://79.120.12.130", "path": "westcoastblues" },
            { "name": "Hip - Hop Soul", "host": "http://79.120.12.130", "path": "hiphopsoul" },
        ]
    },
    {
        "name": "Country",
        "stations": [
            { "name": "Alternative Country", "host": "http://79.111.119.111", "path": "altcountry" },
            { "name": "Bluegrass", "host": "http://79.111.14.76", "path": "bluegrass" },
            { "name": "Country", "host": "http://79.111.119.111", "path": "countrypop" },
            { "name": "Country Pop", "host": "http://79.111.119.111", "path": "countrypop" },
            { "name": "Honky - Tonk", "host": "http://213.141.131.10", "path": "honkytonk" },
            { "name": "Western Swing", "host": "http://79.120.12.130", "path": "westernswing" },
            { "name": "Country Blues", "host": "http://79.120.77.11", "path": "countryblues" },
            { "name": "Country Rock", "host": "http://79.111.119.111", "path": "countryrock" },
            { "name": "Americana", "host": "http://213.141.131.10", "path": "americana" },
        ]
    },
    {
        "name": "Jazz",
        "stations": [
            { "name": "Smooth Jazz", "host": "http://79.120.39.202", "path": "smoothjazz" },
            { "name": "Jazz Funk", "host": "http://79.120.39.202", "path": "jazzfunk" },
            { "name": "Nu Jazz / Future Jazz", "host": "http://79.111.14.76", "path": "nujazz" },
            { "name": "Free Jazz", "host": "http://79.111.14.76", "path": "freejazz" },
            { "name": "Contemporary Jazz", "host": "http://79.111.119.111", "path": "contemporaryjazz" },
            { "name": "Soul Jazz", "host": "http://79.111.14.76", "path": "souljazz" },
            { "name": "Modern Creative", "host": "http://79.120.77.11", "path": "mcreative" },
            { "name": "Swing", "host": "http://79.120.39.202", "path": "strings" },
            { "name": "Vocal Jazz", "host": "http://79.120.39.202", "path": "vocaljazz" },
            { "name": "Hard Bop", "host": "http://79.111.14.76", "path": "hardbop" },
            { "name": "Bossa Nova", "host": "http://79.111.14.76", "path": "bossanova" },
            { "name": "Latin / Afro - Cuban Jazz", "host": "http://79.111.119.111", "path": "latinjazz" },
            { "name": "Jazz Manouche / Gypsy Jazz", "host": "http://79.120.77.11", "path": "manouche" },
            { "name": "Jazz Pop", "host": "http://79.120.39.202", "path": "jazzpop" },
            { "name": "Big Band", "host": "http://79.120.39.202", "path": "bigband" },
            { "name": "Cool / West Coast Jazz", "host": "http://79.120.39.202", "path": "cooljazz" },
            { "name": "Post Bop", "host": "http://79.111.14.76", "path": "postbop" },
            { "name": "Piano Jazz / Stride / Ragtime", "host": "http://79.111.119.111", "path": "pianojazz" },
            { "name": "Avant - Garde Jazz", "host": "http://79.111.119.111", "path": "avantgardejazz" },
            { "name": "Dark / Doom / Noir / Funeral / Ambient Jazz", "host": "http://79.120.39.202", "path": "darkjazz" },
            { "name": "Dixieland", "host": "http://79.120.39.202", "path": "dixieland" },
            { "name": "Acid Jazz", "host": "http://79.111.14.76", "path": "acidjazz" },
            { "name": "Mainstream Jazz", "host": "http://79.111.14.76", "path": "mainstreamjazz" },
            { "name": "Jazz Fusion", "host": "http://79.111.119.111", "path": "jazzfusion" },
            { "name": "Jazz", "host": "http://79.120.77.11", "path": "jazz" },
            { "name": "Guitar Jazz", "host": "http://79.120.77.11", "path": "guitarjazz" },
            { "name": "Ethno / World Jazz", "host": "http://79.120.39.202", "path": "ethnojazz" },
            { "name": "Chamber Jazz", "host": "http://79.120.39.202", "path": "chamberjazz" },
            { "name": "Bebop / Be - Bop / Bop", "host": "http://79.120.12.130", "path": "bebop" },
            { "name": "Style & Sound Ecm Records", "host": "http://213.141.131.10", "path": "ecmrecords" },
            { "name": "Third Stream", "host": "http://213.141.131.10", "path": "thirdstream" },
            { "name": "Crossover Jazz", "host": "http://213.141.131.10", "path": "crossoverjazz" },
            { "name": "Modal Jazz", "host": "http://213.141.131.10", "path": "modaljazz" },
            { "name": "Straight - Ahead Jazz", "host": "http://79.120.12.130", "path": "straightahead" },
            { "name": "Jazz Trumpet", "host": "http://213.141.131.10", "path": "trumpetjazz" },
            { "name": "Vibraphone in Jazz", "host": "http://213.141.131.10", "path": "vibraphone" },
            { "name": "Brazilian Jazz", "host": "http://79.120.12.130", "path": "brazilianjazz" },
            { "name": "Free Funk", "host": "http://79.120.12.130", "path": "freefunk" },
            { "name": "Free Improvisation", "host": "http://79.120.77.11", "path": "freeimprovisation" },
        ]
    },
    {
        "name": "Pop Music",
        "stations": [
            { "name": "Classical Crossover", "host": "http://79.120.77.11", "path": "classcross" },
            { "name": "Russian Pop Music", "host": "http://79.120.77.11", "path": "popru" },
            { "name": "Nu Disco", "host": "http://79.111.119.111", "path": "nudisco" },
            { "name": "Эстрадная Музыка Ссср", "host": "http://79.120.39.202", "path": "bardru" },
            { "name": "Pop Ballads", "host": "http://79.120.77.11", "path": "popballads" },
            { "name": "Pop Music", "host": "http://79.120.77.11", "path": "pop" },
            { "name": "Italo Disco", "host": "http://79.111.119.111", "path": "italodisco" },
            { "name": "J - Pop (Japanese Pop)", "host": "http://79.111.119.111", "path": "jpop" },
            { "name": "Chanson", "host": "http://79.111.14.76", "path": "frenchchanson" },
            { "name": "K - Pop (Korean Pop)", "host": "http://79.111.119.111", "path": "kpop" },
            { "name": "Eurodance", "host": "http://79.120.39.202", "path": "eurodance" },
            { "name": "Euro Disco", "host": "http://79.111.119.111", "path": "eurodisco" },
            { "name": "Disco", "host": "http://79.120.77.11", "path": "disco" },
            { "name": "Russian Pop Music 1980 - 1990's", "host": "http://79.120.77.11", "path": "80ru" },
            { "name": "Arabic Pop Music", "host": "http://79.120.39.202", "path": "arabicpop" },
            { "name": "Latin Pop", "host": "http://79.111.119.111", "path": "latinpop" },
            { "name": "Dance Pop", "host": "http://79.120.77.11", "path": "dancepop" },
            { "name": "Eurobeat / Hi - Nrg", "host": "http://79.120.39.202", "path": "eurobeat" },
            { "name": "Italo Pop", "host": "http://213.141.131.10", "path": "italopop" },
            { "name": "C - Pop (Chinese Pop)", "host": "http://213.141.131.10", "path": "cpop" },
            { "name": "French Pop", "host": "http://79.120.12.130", "path": "frenchpop" },
            { "name": "Schlager", "host": "http://79.111.119.111", "path": "schlager" },
            { "name": "Turkish Pop / Pop Rock", "host": "http://213.141.131.10", "path": "turkishpop" },
            { "name": "Folk Pop", "host": "http://213.141.131.10", "path": "folkpop" },
            { "name": "Reggaeton / Cubaton / Salsaton / Latino...", "host": "http://213.141.131.10", "path": "reggaeton" },
            { "name": "Manele / Romanian Pop Folk / Ethnic", "host": "http://213.141.131.10", "path": "manele" },
            { "name": "Bulgarian Pop - Folk / Ethnopop / Chalga", "host": "http://213.141.131.10", "path": "chalga" },
            { "name": "Traditional / Classic Pop", "host": "http://213.141.131.10", "path": "tradpop" },
            { "name": "Cantopop / Hk - Pop", "host": "http://79.120.12.130", "path": "cantopop" },
            { "name": "Italodance", "host": "http://79.111.14.76", "path": "italodance" },
            { "name": "Mpb (Musica Popular Brasileira)", "host": "http://79.111.14.76", "path": "mpb" },
        ]
    },
    {
        "name": "Rock Music",
        "stations": [
            { "name": "Psychobilly", "host": "http://79.111.119.111", "path": "psychobilly" },
            { "name": "Folk Rock", "host": "http://79.111.14.76", "path": "folkrock" },
            { "name": "Rock & Roll", "host": "http://79.120.77.11", "path": "rockroll" },
            { "name": "Hard Rock", "host": "http://79.120.39.202", "path": "artrock" },
            { "name": "Dream Pop", "host": "http://79.111.14.76", "path": "dreampop" },
            { "name": "Jazz Rock", "host": "http://79.111.119.111", "path": "jazzrock" },
            { "name": "Noise Rock", "host": "http://79.120.39.202", "path": "noiserock" },
            { "name": "Post Rock", "host": "http://79.111.14.76", "path": "postrock" },
            { "name": "Shoegazing", "host": "http://79.111.119.111", "path": "shoegazing" },
            { "name": "Space Rock", "host": "http://79.111.119.111", "path": "spacerock" },
            { "name": "Pop Rock", "host": "http://79.111.14.76", "path": "postrock" },
            { "name": "Indie Rock", "host": "http://79.120.39.202", "path": "indierock" },
            { "name": "Krautrock", "host": "http://79.111.119.111", "path": "krautrock" },
            { "name": "Math Rock", "host": "http://79.120.39.202", "path": "mathrock" },
            { "name": "Horror Punk", "host": "http://79.120.77.11", "path": "horrorpunk" },
            { "name": "Eclectic Prog", "host": "http://79.111.14.76", "path": "eclecticprog" },
            { "name": "Dark Cabaret", "host": "http://79.111.119.111", "path": "darkcabaret" },
            { "name": "Dark Wave", "host": "http://79.111.14.76", "path": "darkwave" },
            { "name": "Celtic Rock", "host": "http://79.120.12.130", "path": "celticrock" },
            { "name": "Roots Rock", "host": "http://79.120.12.130", "path": "rootsrock" },
            { "name": "Garage Punk", "host": "http://79.120.12.130", "path": "garagepunk" },
            { "name": "Indie Folk", "host": "http://79.111.14.76", "path": "indiefolk" },
            { "name": "Surf Rock", "host": "http://79.111.119.111", "path": "surfrock" },
            { "name": "Punk Rock", "host": "http://79.120.77.11", "path": "punk" },
            { "name": "Grunge", "host": "http://79.120.39.202", "path": "grunge" },
            { "name": "New Wave", "host": "http://79.120.77.11", "path": "newage" },
            { "name": "Art Rock", "host": "http://79.120.39.202", "path": "artrock" },
            { "name": "Gothic Rock", "host": "http://79.111.14.76", "path": "gothicrock" },
            { "name": "Post Grunge", "host": "http://79.111.119.111", "path": "postgrunge" },
            { "name": "Garage Rock", "host": "http://79.120.39.202", "path": "artrock" },
            { "name": "Rockabilly", "host": "http://79.111.14.76", "path": "rockabilly" },
            { "name": "Stoner Rock", "host": "http://79.111.119.111", "path": "stonerrock" },
            { "name": "Blues Rock", "host": "http://79.120.39.202", "path": "bluesrock" },
            { "name": "Post Punk", "host": "http://79.111.14.76", "path": "poppunk" },
            { "name": "Pop Punk", "host": "http://79.111.14.76", "path": "poppunk" },
            { "name": "Country Rock", "host": "http://79.111.119.111", "path": "countryrock" },
            { "name": "Twist", "host": "http://79.111.119.111", "path": "twist" },
            { "name": "Acid Rock", "host": "http://213.141.131.10", "path": "acidrock" },
            { "name": "Jam Band", "host": "http://79.120.12.130", "path": "jamband" },
            { "name": "Deathrock", "host": "http://79.120.39.202", "path": "mathrock" },
            { "name": "Pub Rock", "host": "http://79.120.12.130", "path": "pubrock" },
            { "name": "Britpop / Post Britpop", "host": "http://79.120.39.202", "path": "britpop" },
            { "name": "Southern Rock / Metal", "host": "http://79.111.14.76", "path": "southernrock" },
            { "name": "Russian Rock / Bard Rock", "host": "http://79.120.77.11", "path": "rockru" },
            { "name": "Instrumental Rock", "host": "http://79.120.39.202", "path": "instrumentalrock" },
            { "name": "Aor / Melodic Hard Rock", "host": "http://79.111.14.76", "path": "aor" },
            { "name": "Rock / Metal Ballads", "host": "http://79.120.77.11", "path": "rockballads" },
            { "name": "Neo - Progressive Rock", "host": "http://79.111.119.111", "path": "neoprogrock" },
            { "name": "Russian Punk Rock", "host": "http://79.120.77.11", "path": "punkru" },
            { "name": "Classic Rock / Rock", "host": "http://79.120.77.11", "path": "rock" },
            { "name": "Russian Folk Rock", "host": "http://79.111.14.76", "path": "folkrockru" },
            { "name": "Glam Rock / Metal", "host": "http://79.120.39.202", "path": "glam" },
            { "name": "Alternative Rock", "host": "http://79.120.39.202", "path": "altrock" },
            { "name": "Progressive Rock", "host": "http://79.111.119.111", "path": "progressiverock" },
            { "name": "Psychedelic Rock", "host": "http://79.111.119.111", "path": "psychedelicrock" },
            { "name": "Chamber / Baroque / Pop / Rock", "host": "http://79.111.14.76", "path": "chamberpop" },
            { "name": "Avant - Prog / Rock in Opposition (Rio) / Canterbury Scene / Zeuhl Heavy / Hard Psychedelic", "host": "http://79.111.119.111", "path": "avantprog" },
            { "name": "Slowcore / Sadcore", "host": "http://213.141.131.10", "path": "slowcore" },
            { "name": "Progressive Folk", "host": "http://213.141.131.10", "path": "progfolk" },
            { "name": "Psychedelic Folk", "host": "http://213.141.131.10", "path": "psychfolk" },
            { "name": "J - Rock (Japanese Rock)", "host": "http://79.111.119.111", "path": "jrock" },
            { "name": "Dance / Disco / Funk Punk", "host": "http://213.141.131.10", "path": "dancepunk" },
            { "name": "Experimental / Avant Rock", "host": "http://213.141.131.10", "path": "avantrock" },
            { "name": "Folk / Celtic / Gypsy Punk", "host": "http://213.141.131.10", "path": "folkpunk" },
            { "name": "Funk Rock / Metal", "host": "http://213.141.131.10", "path": "funkrock" },
            { "name": "Visual / Nagoya / Oshare / Angura Kei", "host": "http://79.120.12.130", "path": "visualkei" },
            { "name": "Indie / Twee Pop", "host": "http://79.111.119.111", "path": "indiepop" },
            { "name": "Oi! / Street Punk", "host": "http://79.111.119.111", "path": "oistreetpunk" },
            { "name": "Piano Rock / Pop", "host": "http://79.111.14.76", "path": "pianorock" },
            { "name": "Ethereal Wave", "host": "http://213.141.131.10", "path": "ethereal" },
            { "name": "Christian Rock", "host": "http://213.141.131.10", "path": "christianrock" },
            { "name": "Crossover Prog", "host": "http://79.111.14.76", "path": "crossoverprog" },
            { "name": "Symphonic Rock", "host": "http://79.120.39.202", "path": "symphorock" },
            { "name": "Industrial Rock", "host": "http://79.120.77.11", "path": "industrialrock" },
            { "name": "Heavy / Hard Prog", "host": "http://79.111.14.76", "path": "heavyprog" },
            { "name": "Rpi (Rock Progressivo Italiano)", "host": "http://79.111.14.76", "path": "rpi" },
        ]
    },
    {
        "name": "Reggae / Ska",
        "stations": [
            { "name": "Reggae", "host": "http://79.120.39.202", "path": "reggae" },
            { "name": "Ska", "host": "http://79.111.119.111", "path": "ska" },
            { "name": "Dub", "host": "http://79.111.14.76", "path": "dub" },
            { "name": "Ska Punk / Core", "host": "http://79.111.119.111", "path": "skapunk" },
            { "name": "Dancehall / Raggamuffin", "host": "http://79.111.14.76", "path": "dancehall" },
            { "name": "Roots Reggae", "host": "http://79.111.119.111", "path": "rootsreggae" },
            { "name": "Rocksteady / Lovers Rock", "host": "http://79.120.39.202", "path": "rocksteady" },
        ]
    },
    {
        "name": "Metal",
        "stations": [
            { "name": "Groove Metal", "host": "http://79.120.39.202", "path": "groovemetal" },
            { "name": "Dark Metal", "host": "http://79.111.119.111", "path": "darkmetal" },
            { "name": "Doom Metal", "host": "http://79.120.39.202", "path": "deathdoom" },
            { "name": "Death Metal", "host": "http://79.120.77.11", "path": "deathmetal" },
            { "name": "Power Metal", "host": "http://79.120.77.11", "path": "powermetal" },
            { "name": "Gothic Metal", "host": "http://79.120.77.11", "path": "gothicmetal" },
            { "name": "Speed Metal", "host": "http://79.111.119.111", "path": "speedmetal" },
            { "name": "Folk Metal", "host": "http://79.120.39.202", "path": "folkmetal" },
            { "name": "Epic Metal", "host": "http://79.111.119.111", "path": "epicmetal" },
            { "name": "Death 'n' Roll", "host": "http://79.120.39.202", "path": "deathnroll" },
            { "name": "Post Metal", "host": "http://79.120.39.202", "path": "postmetal" },
            { "name": "Black Metal", "host": "http://79.120.77.11", "path": "blackmetal" },
            { "name": "Alt / Nu Metal", "host": "http://79.111.14.76", "path": "numetal" },
            { "name": "Sludge Metal", "host": "http://79.120.77.11", "path": "sludgemetal" },
            { "name": "Heavy Metal", "host": "http://79.111.14.76", "path": "heavymetal" },
            { "name": "Stoner Metal", "host": "http://79.120.77.11", "path": "powermetal" },
            { "name": "Pagan Metal", "host": "http://79.111.119.111", "path": "paganmetal" },
            { "name": "Viking Metal", "host": "http://79.111.14.76", "path": "vikingmetal" },
            { "name": "Nwobhm", "host": "http://79.120.12.130", "path": "nwobhm" },
            { "name": "Speed Heavy", "host": "http://213.141.131.10", "path": "speedheavy" },
            { "name": "Celtic Metal", "host": "http://79.120.12.130", "path": "celticmetal" },
            { "name": "Symphonic Black Metal", "host": "http://79.111.119.111", "path": "symphonicblackmetal" },
            { "name": "Neoclassical Metal", "host": "http://79.111.119.111", "path": "neoclassicalmetal" },
            { "name": "Progressive Black / Post - Black / Blackgaze", "host": "http://79.111.14.76", "path": "postblack" },
            { "name": "Progressive Death Metal", "host": "http://79.111.119.111", "path": "progdeath" },
            { "name": "Black / Blackened Death", "host": "http://79.111.14.76", "path": "blackdeath" },
            { "name": "Instrumental Metal", "host": "http://79.111.119.111", "path": "instrumentalmetal" },
            { "name": "Avant - Garde Metal", "host": "http://79.111.14.76", "path": "avantgardemetal" },
            { "name": "Progressive Metal", "host": "http://79.120.77.11", "path": "progmetal" },
            { "name": "Thrash Metal", "host": "http://79.120.77.11", "path": "thrashmetal" },
            { "name": "Brutal / Slamming Brutal Death", "host": "http://79.111.119.111", "path": "brutaldeathmetal" },
            { "name": "Drone / Drone Doom Metal", "host": "http://79.120.39.202", "path": "dronemetal" },
            { "name": "Depressive Black Metal", "host": "http://79.111.119.111", "path": "dsbm" },
            { "name": "Industrial / Cyber Metal", "host": "http://79.120.39.202", "path": "industrialmetal" },
            { "name": "Melodic Death Metal", "host": "http://79.120.77.11", "path": "melodicdeath" },
            { "name": "Technical Death Metal", "host": "http://79.120.77.11", "path": "techdeathmetal" },
            { "name": "Melodic Black Metal", "host": "http://79.111.119.111", "path": "melodicblackmetal" },
            { "name": "Atmospheric / Ambient Black", "host": "http://79.120.39.202", "path": "aabmds" },
            { "name": "Math Metal / Djent", "host": "http://79.120.39.202", "path": "mathmetal" },
            { "name": "Female Vocal in Metal", "host": "http://79.111.14.76", "path": "femalemetal" },
            { "name": "Death Doom Metal", "host": "http://79.120.39.202", "path": "deathdoom" },
            { "name": "Funeral Doom Metal", "host": "http://79.120.77.11", "path": "funeraldoom" },
            { "name": "Black / Blackened Doom", "host": "http://79.120.77.11", "path": "blackdoom" },
            { "name": "Gothic Doom Metal", "host": "http://79.120.39.202", "path": "gothdoommet" },
            { "name": "Progressive Power Metal", "host": "http://79.111.119.111", "path": "progpowermetal" },
            { "name": "Heavy Power Metal", "host": "http://79.120.12.130", "path": "heavypowermetal" },
            { "name": "Melodic Heavy Metal", "host": "http://79.111.119.111", "path": "melodicheavy" },
            { "name": "Melodic Power Metal", "host": "http://79.111.119.111", "path": "melodicpower" },
            { "name": "Thrash Death Metal", "host": "http://79.120.12.130", "path": "thrashdeath" },
            { "name": "Neue Deutsche Härte", "host": "http://213.141.131.10", "path": "ndh" },
            { "name": "Symphonic Power Metal", "host": "http://213.141.131.10", "path": "symphopower" },
            { "name": "Progressive Heavy Metal", "host": "http://213.141.131.10", "path": "progheavy" },
            { "name": "Thrash Heavy Metal", "host": "http://213.141.131.10", "path": "thrashheavy" },
            { "name": "Thrash Black Metal", "host": "http://213.141.131.10", "path": "thrashblack" },
            { "name": "Symphonic Death Metal", "host": "http://213.141.131.10", "path": "symphodeath" },
            { "name": "Symphonic Gothic Metal", "host": "http://213.141.131.10", "path": "symphogoth" },
            { "name": "Crossover Thrash", "host": "http://213.141.131.10", "path": "crossoverthrash" },
            { "name": "Atmospheric Doom", "host": "http://213.141.131.10", "path": "atmosphericdoom" },
            { "name": "Jazz / Fusion Metal", "host": "http://213.141.131.10", "path": "jazzmetal" },
            { "name": "Medieval Metal / Rock", "host": "http://213.141.131.10", "path": "medievalmetal" },
            { "name": "Avant - Garde Black Metal", "host": "http://79.120.39.202", "path": "avantblackmet" },
            { "name": "Gothic Black Metal", "host": "http://79.120.39.202", "path": "gothblackmet" },
            { "name": "Gothic Death Metal", "host": "http://79.120.39.202", "path": "gothdeathmet" },
            { "name": "Symphonic Metal", "host": "http://79.120.77.11", "path": "symphometal" },
            { "name": "Oriental Metal", "host": "http://79.111.119.111", "path": "orientalmetal" },
            { "name": "Melodic Doom / Doom Death", "host": "http://79.120.12.130", "path": "melodicdoom" },
            { "name": "Folk Black Metal", "host": "http://79.120.12.130", "path": "folkblackmet" },
            { "name": "Folk Death Metal", "host": "http://79.120.12.130", "path": "folkdeathmet" },
        ]
    },
    {
        "name": "Hardcore",
        "stations": [
            { "name": "Deathcore / Melodic Deathcore", "host": "http://79.111.14.76", "path": "deathcore" },
            { "name": "Crust Punk / Stenchcore", "host": "http://79.120.39.202", "path": "crust" },
            { "name": "Rapcore", "host": "http://79.111.119.111", "path": "breakcore" },
            { "name": "Metalcore", "host": "http://79.120.39.202", "path": "metalcore" },
            { "name": "Emocore / Screamo / EMO Violence", "host": "http://79.111.119.111", "path": "screamoemo" },
            { "name": "Progressive Metalcore", "host": "http://79.111.14.76", "path": "progmetalcore" },
            { "name": "Post Hardcore", "host": "http://79.111.119.111", "path": "posthardcore" },
            { "name": "Grindcore / Deathgrind", "host": "http://79.120.77.11", "path": "grindcore" },
            { "name": "Melodic Metalcore", "host": "http://79.111.14.76", "path": "melodicmetalcore" },
            { "name": "Mathcore / Chaotic Hardcore", "host": "http://79.120.39.202", "path": "mathcore" },
            { "name": "Hardcore / Melodic Hardcore", "host": "http://79.111.14.76", "path": "hardcoremetal" },
            { "name": "Electronicore / Synthcore / Trancecore", "host": "http://79.111.119.111", "path": "electronicore" },
            { "name": "Beatdown / Moshcore / Downtempo Hardcore / Metalcore", "host": "http://79.111.14.76", "path": "beatdown" },
        ]
    },
    {
        "name": "Electronic Music",
        "stations": [
            { "name": "Hardstyle", "host": "http://79.111.14.76", "path": "hardstyle" },
            { "name": "Lo - Fi", "host": "http://79.111.14.76", "path": "lo-fi" },
            { "name": "Ambient Dub", "host": "http://79.111.14.76", "path": "ambientdub" },
            { "name": "Ambient", "host": "http://79.111.119.111", "path": "ambient" },
            { "name": "Electroclash", "host": "http://79.120.39.202", "path": "electroclash" },
            { "name": "Dark Dubstep", "host": "http://79.120.39.202", "path": "darkdubstep" },
            { "name": "Trance", "host": "http://79.120.77.11", "path": "trance" },
            { "name": "Chill Out", "host": "http://79.111.14.76", "path": "chillout" },
            { "name": "Chiptune", "host": "http://79.111.119.111", "path": "chiptune" },
            { "name": "Vocal Trance", "host": "http://79.120.39.202", "path": "vocaltrance" },
            { "name": "Psybient", "host": "http://79.111.119.111", "path": "ambient" },
            { "name": "New Age", "host": "http://79.120.77.11", "path": "newage" },
            { "name": "Lounge", "host": "http://79.111.14.76", "path": "lounge" },
            { "name": "Psytrance", "host": "http://79.111.119.111", "path": "psytrance" },
            { "name": "Deathstep", "host": "http://79.120.39.202", "path": "dubstep" },
            { "name": "Space Music", "host": "http://79.111.119.111", "path": "spacemusic" },
            { "name": "Dubstep", "host": "http://79.120.39.202", "path": "dubstep" },
            { "name": "Broken Beat", "host": "http://79.120.77.11", "path": "brokenbeat" },
            { "name": "Leftfield", "host": "http://79.120.39.202", "path": "leftfield" },
            { "name": "Tribal House", "host": "http://213.141.131.10", "path": "tribalhouse" },
            { "name": "Funky House", "host": "http://213.141.131.10", "path": "funkyhouse" },
            { "name": "Nitzhonot", "host": "http://213.141.131.10", "path": "nitzhonot" },
            { "name": "Garage House", "host": "http://213.141.131.10", "path": "hardhouse" },
            { "name": "Full on", "host": "http://79.111.14.76", "path": "fullon" },
            { "name": "Goa Trance", "host": "http://79.120.39.202", "path": "goatrance" },
            { "name": "Techno", "host": "http://79.120.77.11", "path": "techno" },
            { "name": "Electro", "host": "http://79.111.119.111", "path": "electro" },
            { "name": "Spacesynth", "host": "http://79.111.119.111", "path": "spacemusic" },
            { "name": "Euro House", "host": "http://79.111.119.111", "path": "eurohouse" },
            { "name": "Dub Techno", "host": "http://79.120.39.202", "path": "dubtechno" },
            { "name": "Dream Trance", "host": "http://79.120.39.202", "path": "dreamtrance" },
            { "name": "Trip - Hop", "host": "http://79.111.14.76", "path": "triphop" },
            { "name": "Industrial", "host": "http://79.111.14.76", "path": "industrial" },
            { "name": "Downtempo", "host": "http://79.120.77.11", "path": "downtempo" },
            { "name": "Grime", "host": "http://79.120.77.11", "path": "grime" },
            { "name": "Dark Techno", "host": "http://79.111.14.76", "path": "darktechno" },
            { "name": "Witch House", "host": "http://79.120.77.11", "path": "witchhouse" },
            { "name": "Club Dance", "host": "http://79.111.119.111", "path": "clubdance" },
            { "name": "Hard Trance", "host": "http://79.120.77.11", "path": "hardtrance" },
            { "name": "Drumstep", "host": "http://79.120.39.202", "path": "drumstep" },
            { "name": "House", "host": "http://79.120.77.11", "path": "house" },
            { "name": "Drum & Bass", "host": "http://79.111.14.76", "path": "drumbass" },
            { "name": "Futurepop", "host": "http://79.120.39.202", "path": "futurepop" },
            { "name": "Breakcore", "host": "http://79.111.119.111", "path": "breakcore" },
            { "name": "EDM Trap", "host": "http://213.141.131.10", "path": "edmtrap" },
            { "name": "Hard House", "host": "http://213.141.131.10", "path": "hardhouse" },
            { "name": "Illbient", "host": "http://213.141.131.10", "path": "illbient" },
            { "name": "IDM Ambient", "host": "http://213.141.131.10", "path": "idmambient" },
            { "name": "Cyberpunk", "host": "http://79.120.12.130", "path": "cyberpunk" },
            { "name": "Jumpstyle", "host": "http://79.120.12.130", "path": "jumpstyle" },
            { "name": "Makina", "host": "http://79.120.12.130", "path": "makina" },
            { "name": "New Beat", "host": "http://79.120.12.130", "path": "newbeat" },
            { "name": "Freestyle", "host": "http://79.120.12.130", "path": "freestyle" },
            { "name": "Harsh Noise", "host": "http://79.111.14.76", "path": "harshnoise" },
            { "name": "Metalstep / Brostep / Metal Dubstep", "host": "http://79.111.14.76", "path": "metalstep" },
            { "name": "Progressive Trance", "host": "http://79.120.39.202", "path": "progtrance" },
            { "name": "Russian Club Dance", "host": "http://79.120.77.11", "path": "clubru" },
            { "name": "Neurofunk / Technoid / Techstep", "host": "http://79.111.119.111", "path": "neurofunk" },
            { "name": "IDM (Intelligent Dance Music)", "host": "http://79.111.14.76", "path": "idm" },
            { "name": "Progressive Psytrance", "host": "http://79.120.39.202", "path": "progtrance" },
            { "name": "Dark Electro / Aggrotech", "host": "http://79.120.39.202", "path": "darkelectro" },
            { "name": "Breakbeat / Big Beat", "host": "http://79.120.39.202", "path": "breakbeat" },
            { "name": "Hardcore Techno / Schranz", "host": "http://79.120.39.202", "path": "hardcoretech" },
            { "name": "EBM (Electronic Body Music)", "host": "http://79.111.14.76", "path": "ebm" },
            { "name": "Dark / Neo / Apocalyptic Folk", "host": "http://79.111.119.111", "path": "darkfolk" },
            { "name": "Indie Electronic / New Rave", "host": "http://79.111.119.111", "path": "indieelectronic" },
            { "name": "Happy / UK Hardcore", "host": "http://79.120.77.11", "path": "happyhardcore" },
            { "name": "Minimal Tech House", "host": "http://79.111.119.111", "path": "mintechhouse" },
            { "name": "Retrowave / Synthwave / Dreamwave", "host": "http://79.120.39.202", "path": "retrowave" },
            { "name": "Glitch / Glitch - Hop", "host": "http://79.111.14.76", "path": "glitch" },
            { "name": "Future Garage / Chillstep / Deepstep", "host": "http://79.120.39.202", "path": "futuregarage" },
            { "name": "Industrial / Dark / Ritual Ambient", "host": "http://79.120.39.202", "path": "darkambient" },
            { "name": "Synthpop / Electropop / Technopop", "host": "http://79.120.77.11", "path": "synthpop" },
            { "name": "Progressive House", "host": "http://79.111.119.111", "path": "proghouse" },
            { "name": "Intelligent / Liquid Funk", "host": "http://79.111.119.111", "path": "liquidfunk" },
            { "name": "Electro - Industrial", "host": "http://79.111.119.111", "path": "electroindustrial" },
            { "name": "Deep / Chill House", "host": "http://79.120.39.202", "path": "deephouse" },
            { "name": "Traditional Electronic", "host": "http://79.111.14.76", "path": "tradelectronic" },
            { "name": "Ethnic Electronica", "host": "http://79.120.39.202", "path": "ethnotronica" },
            { "name": "Suomisaundi / Freeform Psytrance", "host": "http://79.120.77.11", "path": "suomisaundi" },
            { "name": "Acid House / Trance / Techno", "host": "http://79.111.119.111", "path": "acid" },
            { "name": "Ambient / Intelligent Techno / House", "host": "http://79.120.39.202", "path": "ambienttechno" },
            { "name": "Martial Industrial / Military Pop", "host": "http://79.111.14.76", "path": "martialindustrial" },
            { "name": "Power / Rhythmic Noise / Dbm (Distorted Beat Music)", "host": "http://79.120.39.202", "path": "powernoise" },
            { "name": "Musique Concrete / Acousmatic / Electroacoustic", "host": "http://213.141.131.10", "path": "musiqueconcrete" },
            { "name": "Future Bass / Chill Trap", "host": "http://213.141.131.10", "path": "futurebass" },
            { "name": "Enigmatic / Mystic Pop", "host": "http://213.141.131.10", "path": "enigmatic" },
            { "name": "Detroit Techno / Tech House", "host": "http://213.141.131.10", "path": "detroittechno" },
            { "name": "Underground Techno / Tech House", "host": "http://213.141.131.10", "path": "undergroundtechno" },
            { "name": "Forest Psytrance", "host": "http://213.141.131.10", "path": "forestpsytrance" },
            { "name": "Jungle / Ragga Jungle / Raggacore", "host": "http://213.141.131.10", "path": "jungle" },
            { "name": "Chillwave / Vaporwave", "host": "http://79.111.119.111", "path": "chillwave" },
            { "name": "Experimental Techno", "host": "http://213.141.131.10", "path": "experimentaltechno" },
            { "name": "Techno Trance / Techtrance", "host": "http://213.141.131.10", "path": "techtrance" },
            { "name": "Night Full on / Psytrance", "host": "http://213.141.131.10", "path": "nightpsytrance" },
            { "name": "Electro Swing / Swing House", "host": "http://213.141.131.10", "path": "electroswing" },
            { "name": "Gabber / Early / Mainstream Hardcore", "host": "http://213.141.131.10", "path": "gabber" },
            { "name": "Darksynth / Dark Synthwave", "host": "http://213.141.131.10", "path": "darksynth" },
            { "name": "Progressive Electronic", "host": "http://79.120.12.130", "path": "progelectronic" },
            { "name": "Twilight / Psytrance", "host": "http://79.120.12.130", "path": "twilightpsy" },
            { "name": "Dungeon Synth", "host": "http://79.120.12.130", "path": "dungeonsynth" },
            { "name": "Hi - Tech / Psytrance", "host": "http://79.120.12.130", "path": "hitechpsy" },
            { "name": "Industrial Techno", "host": "http://79.120.12.130", "path": "industrialtechno" },
            { "name": "Uplifting / Epic / Euphoric Trance", "host": "http://79.111.119.111", "path": "upliftingtrance" },
            { "name": "Drone Ambient", "host": "http://79.111.119.111", "path": "droneambient" },
            { "name": "Pumping House", "host": "http://79.120.12.130", "path": "ambienthouse" },
            { "name": "Riddim Dubstep", "host": "http://79.111.119.111", "path": "riddimdubstep" },
            { "name": "Soulful House", "host": "http://79.111.119.111", "path": "soulfulhouse" },
            { "name": "Minimal Techno", "host": "http://79.120.39.202", "path": "mintechno" },
            { "name": "Field Recordings", "host": "http://213.141.131.10", "path": "fieldrecording" },
            { "name": "Electro Techno", "host": "http://213.141.131.10", "path": "electrotechno" },
            { "name": "Electro House", "host": "http://79.111.14.76", "path": "electrohouse" },
            { "name": "Dark Psytrance", "host": "http://79.111.119.111", "path": "darkpsytrance" },
            { "name": "Balearic Beat / House | Ibiza House / Chillout", "host": "http://213.141.131.10", "path": "balearichouse" },
            { "name": "Big Room House", "host": "http://213.141.131.10", "path": "bigroomhouse" },
            { "name": "Ambient House", "host": "http://79.120.12.130", "path": "ambienthouse" },
            { "name": "Progressive / Atmospheric Breaks", "host": "http://79.120.12.130", "path": "progbreaks" },
            { "name": "Melodic House / Techno", "host": "http://79.120.12.130", "path": "melodichouse" },
            { "name": "Organic House", "host": "http://79.120.12.130", "path": "organichouse" },
            { "name": "Latin House / EDM", "host": "http://79.120.12.130", "path": "latinhouse" },
            { "name": "Ghetto / Booty / G - House", "host": "http://79.111.14.76", "path": "ghouse" },
            { "name": "Power Electronics / Death Industrial", "host": "http://79.111.14.76", "path": "powerelectronics" },
        ]
    },
    {
        "name": "Rap / Hip - Hop",
        "stations": [
            { "name": "Hip - Hop", "host": "http://79.120.77.11", "path": "hiphop" },
            { "name": "West Coast / Gangsta / G - Funk", "host": "http://79.120.39.202", "path": "gangstarap" },
            { "name": "Instrumental Hip - Hop", "host": "http://79.120.77.11", "path": "instrumentalhiphop" },
            { "name": "Russian Rap", "host": "http://79.120.77.11", "path": "rapru" },
            { "name": "Rap", "host": "http://79.120.77.11", "path": "rap" },
            { "name": "Underground Rap", "host": "http://79.111.14.76", "path": "undergroundrap" },
            { "name": "Alternative / Abstract / Experimental Hip - Hop", "host": "http://79.111.14.76", "path": "abstracthiphop" },
            { "name": "Southern Rap / Hip - Hop / Crunk", "host": "http://79.111.119.111", "path": "southernrap" },
            { "name": "East Coast Rap", "host": "http://79.111.14.76", "path": "eastcoastrap" },
            { "name": "Jazz Rap / Jazz Hop / Jazzy Hip - Hop", "host": "http://79.120.39.202", "path": "jazzrap" },
            { "name": "Hardcore Rap / Horrorcore", "host": "http://79.120.39.202", "path": "hardcorerap" },
            { "name": "Memphis Rap", "host": "http://213.141.131.10", "path": "memphisrap" },
            { "name": "German / Deutsche Hip - Hop / Rap", "host": "http://213.141.131.10", "path": "germanrap" },
            { "name": "French Hip - Hop / Rap", "host": "http://213.141.131.10", "path": "frenchrap" },
            { "name": "UK / British Hip - Hop / Rap", "host": "http://213.141.131.10", "path": "ukhiphop" },
            { "name": "Old School Hip - Hop", "host": "http://213.141.131.10", "path": "oldschoolhiphop" },
            { "name": "Cloud Rap / Trillwave", "host": "http://213.141.131.10", "path": "cloudrap" },
            { "name": "Chicano Rap", "host": "http://213.141.131.10", "path": "chicanorap" },
            { "name": "Phonk / Drift Phonk", "host": "http://79.120.77.11", "path": "phonk" },
        ]
    },
    {
        "name": "Шансон",
        "stations": [
            { "name": "Русский Шансон", "host": "http://79.120.39.202", "path": "bardru" },
            { "name": "Русский Постшансон", "host": "http://79.120.39.202", "path": "bardru" },
            { "name": "Цыганская Песня", "host": "http://79.120.39.202", "path": "bardru" },
            { "name": "Русский / Городской / Жестокий / Романс", "host": "http://79.120.39.202", "path": "bardru" },
            { "name": "Авторская / Бардовская Песня", "host": "http://79.120.39.202", "path": "bardru" },
        ]
    },
    {
        "name": "Miscellaneous Music",
        "stations": [
            { "name": "Oldies", "host": "http://213.141.131.10", "path": "medieval" },
            { "name": "Modern Classical", "host": "http://79.120.39.202", "path": "modernclassical" },
            { "name": "Vocal", "host": "http://79.120.77.11", "path": "vocal" },
            { "name": "Piano", "host": "http://79.120.77.11", "path": "piano" },
            { "name": "Experimental / Avant - Garde Music", "host": "http://79.111.119.111", "path": "experimentalmusic" },
            { "name": "Computer / Video Game Music", "host": "http://79.120.39.202", "path": "musicgame" },
            { "name": "Acoustic Guitar", "host": "http://79.120.39.202", "path": "acousticguitar" },
            { "name": "Neoclassical Music", "host": "http://79.120.39.202", "path": "neoclassical" },
            { "name": "Sounds of Nature", "host": "http://79.111.14.76", "path": "soundnat" },
            { "name": "Saxophone", "host": "http://79.120.77.11", "path": "saxophone" },
            { "name": "Misc", "host": "http://79.120.77.11", "path": "disco" },
            { "name": "Военные Песни / Марши России", "host": "http://79.120.39.202", "path": "bardru" },
            { "name": "Hammond Organ", "host": "http://79.120.77.11", "path": "organ" },
            { "name": "Ballroom Dance", "host": "http://79.111.14.76", "path": "ballroomdance" },
            { "name": "Instrumental Music", "host": "http://79.120.77.11", "path": "instrumental" },
            { "name": "Поэзия", "host": "http://79.120.39.202", "path": "bardru" },
            { "name": "Accordion / Баян / Гармонь", "host": "http://79.111.119.111", "path": "accordion" },
            { "name": "Indian Cinema Music", "host": "http://79.120.39.202", "path": "indiancinema" },
            { "name": "Relaxation Music", "host": "http://79.120.39.202", "path": "relaxation" },
            { "name": "Flute", "host": "http://79.111.14.76", "path": "flute" },
            { "name": "Easy Listening", "host": "http://79.111.14.76", "path": "easylistening" },
            { "name": "Romantic Music Collection", "host": "http://79.120.39.202", "path": "romantic" },
            { "name": "Erotic Music", "host": "http://79.120.39.202", "path": "erotic" },
            { "name": "Meditation Music", "host": "http://79.120.77.11", "path": "meditation" },
            { "name": "Trailer Music", "host": "http://79.111.119.111", "path": "trailer" },
            { "name": "Anime Ost / Score", "host": "http://79.111.119.111", "path": "anime" },
            { "name": "Love Songs", "host": "http://213.141.131.10", "path": "lovesongs" },
            { "name": "Singer - Songwriter", "host": "http://213.141.131.10", "path": "singersongwriter" },
            { "name": "Acoustic & Unplugged", "host": "http://213.141.131.10", "path": "acoustic" },
            { "name": "Healing Music (Yoga, Reiki, Zen, ...)", "host": "http://213.141.131.10", "path": "healing" },
            { "name": "60's Collection", "host": "http://213.141.131.10", "path": "60collection" },
            { "name": "70's Collection", "host": "http://213.141.131.10", "path": "70collection" },
            { "name": "80's Collection", "host": "http://79.120.39.202", "path": "pop80" },
            { "name": "90's Collection", "host": "http://213.141.131.10", "path": "90collection" },
            { "name": "2000's Collection", "host": "http://79.120.12.130", "path": "00collection" },
            { "name": "Prog Related", "host": "http://79.111.14.76", "path": "progrelated" },
        ]
    }
]

// No longer exporting combined categories - use somafmCategories and radcapCategories separately
